services:
  - type: web
    name: tiffin-service-backend
    env: docker
    plan: free
    repo: https://github.com/mangeshvajale6340/TiffinServiceBackend
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
